### ISSUE TITLE
Font Error

### ISSUE THREAD

**Issue by Puggy8893** [Tomato6966/Discord-Welcome-Images#5]
Whenever A user joins it shows the image, but the words arent there...

**Comment by Puggy8893** [comment]
![image](https://user-images.githubusercontent.com/87098896/124848182-f464ca80-df61-11eb-8a87-a61a73225e53.png)
![image](https://user-images.githubusercontent.com/87098896/124848194-fc246f00-df61-11eb-92b5-d0d1cfa47e4b.png)

**Comment by Tomato6966** [comment]
Thats because replit is a free hosting company which doesnt have a complete os aka no default fonts, so use the canvas function registerFont to register a custom Font
```
const { registerFont, createCanvas } = require('canvas')
registerFont('comicsans.ttf', { family: 'Comic Sans' })

const canvas = createCanvas(500, 500)
const ctx = canvas.getContext('2d')

ctx.font = '12px "Comic Sans"'
ctx.fillText('Everyone hates this font :(', 250, 10)
```

U have to have the Font-File (here `comicsans.ttf`) in the Same Directory as where u register the Font

I suggest you to do that on the BOT START

**Comment by Puggy8893** [comment]
![image](https://user-images.githubusercontent.com/87098896/124929042-cca74e00-dfc5-11eb-9c13-7c227876ea49.png)
